# Utiliser Ubuntu comme image de base
FROM ubuntu:latest

# Mettre à jour APT
RUN apt-get update

# Mettre à jour tous les paquets installés
RUN apt-get upgrade -y

# Commande exécutée quand le conteneur démarre
CMD echo "Hello, World!"
